name: modi
description: A mood diary
publish_to: 'none'
version: 1.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  firebase_messaging: ^11.1.0
  firebase_analytics: ^8.3.4
  firebase_remote_config: ^0.11.0+2
  google_mobile_ads: ^1.0.1
  get_it: ^7.2.0
  provider: ^6.0.1
  http: ^0.13.4
  easy_localization: ^3.0.0
  easy_logger: ^0.0.2
  google_sign_in: ^5.2.0
  sign_in_with_apple: ^3.2.0
  flutter_svg: ^0.23.0+1
  scrollable_positioned_list: ^0.3.2
  crypto: ^3.0.1
  url_launcher: ^6.0.17
  package_info_plus: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/translations/
    - assets/svg/

  fonts:
    - family: Kodchasan
      fonts:
        - asset: assets/fonts/Kodchasan-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Kodchasan-Light.ttf
          weight: 300
        - asset: assets/fonts/Kodchasan-Regular.ttf
          weight: 400
        - asset: assets/fonts/Kodchasan-Medium.ttf
          weight: 500
        - asset: assets/fonts/Kodchasan-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Kodchasan-Bold.ttf
          weight: 700
